version: '3'

tasks:
  standard:
    desc: Run tests with standard output verbosity
    aliases:
      - "std"
    cmds:
      - go test ./... -race -p 1
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
  full:
    desc: Run tests with increased output verbosity
    cmds:
      - go test ./... -race -p 1 -v
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
  cover:
    desc: Run tests and build coverage report
    cmds:
      - mkdir -p ../target/tests
      - go test ./... -race -p 1 -v -covermode atomic -coverprofile ../target/tests/cover.out
      - go tool cover -html ../target/tests/cover.out -o ../target/tests/cover.html
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    
