name: Build development docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"

jobs:
  deploy:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Prepare required Python packages
        run: task docs:requirements
      - name: Build and deploy documentation
        run: task docs:deploy-dev
